dist: bionic
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - DJANGO_VERSION=1.11.20
  - DJANGO_VERSION=2.2.8
  - DJANGO_VERSION=3.0
matrix:
  exclude:
  - python: "2.7"
    env: DJANGO_VERSION=2.2.8
  - python: "2.7"
    env: DJANGO_VERSION=3.0
install:
  - pip install -q --upgrade pip
  - pip install -q coveralls
  - pip install -q beautifulsoup4
  - pip install -q Pillow
  - pip install -q Wand
  - pip install -q Django==$DJANGO_VERSION
  - pip install -q lxml
  - pip install -q django-crispy-forms
  - pip install -q docutils
before_install:
  # - sudo add-apt-repository -y ppa:mc3man/trusty-media
  - sudo apt-get update -qq
  - sudo apt-get -y install ffmpeg libjpeg8 libjpeg8-dev libgdal-dev
script:
  - python setup.py check --restructuredtext
  - coverage run --source='smartfields' setup.py test
after_success:
  coveralls
notifications:
  email:
    recipients:
      - lehins@yandex.ru
    on_success: never
    on_failure: always
branches:
  except:
    - /^v[0-9].[0-9].[0-9]/

